---
- name: Create folder
  ansible.builtin.file:
    state: directory
    path: /config
- name: Create file
  ansible.builtin.file:
    state: touch
    path: /config/config.txt
    creates: /config/config.txt
- name: Write to file
  ansible.builtin.lineinfile:
    state: present
    path: /config/config.txt
    line: "{{ basic_role_sentence }}"
- name: Check file content
  ansible.builtin.shell:
    cmd: cat /config/config.txt
  register: file_content
- name: Debug file content
  ansible.builtin.debug:
    var: file_content.stdout
